---
- name: Install qpdfview
  apt:
    name: qpdfview
    state: latest

- name: Copy qpdfview config files
  become: no
<<<<<<< HEAD
  copy:
    src: qpdfview/
    dest: ~/.config/qpdfview/
=======
  copy: src=qpdfview/ dest=~/.config/qpdfview/
>>>>>>> e5ad9563e838c2f8a44f6ebadec16991418b17a7
