---
- name: clone chbright repository
  git:
    repo: https://github.com/gsvitins/chbright.git
    dest: /home/{{ chbright_user }}/git/chbright

- name: link cloned 'chbright' script to /usr/bin/chbright
  file:
    src: /home/{{ chbright_user }}/git/chbright/chbright
    dest: /usr/bin/chbright
    state: link
    owner: root
    group: root
    mode: 0755

- name: create xfce4 keyboard shortcut for chbright
  lineinfile:
    dest: /home/{{ chbright_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    insertafter: "^.*xfce4-screenshooter -w"
    line: '      <property name="&lt;Shift&gt;&lt;Alt&gt;Right" type="string" value="sudo chbright -i 1"/>'
