---
- name: provision desktop
  hosts: lasusvm
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    docker_users: bxz
    terminator_user: bxz
    mount_data_dir: false
    virtualbox_version: 5.2
  roles:
    #    - common
    #- compton
    #- docker
    #- pulseaudio-equalizer
    #- qpdfview
    #- skype
    #- spotify
    #- sshd
    #- terminator
    #- vagrant
    - virtualbox
    #- chbright

