---
- name: provision desktop
  hosts: lasus
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    docker_users: bxz
    terminator_user: bxz
    mount_data_dir: false
  roles:
    - common
    - compton
    - docker
    - pulseaudio-equalizer
    - qpdfview
    - skype
    - spotify
    - sshd
    - terminator
    - vagrant
    - virtualbox
    - chbright

