---
- name: provision desktop
  hosts: all
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    docker_users: bxz
    terminator_user: bxz
    mount_data_dir: false
    virtualbox_version: 6.0
    vagrant_version: 2.2.19
  roles:
    - common
    - compton
    - docker
    - docker-compose
    - qpdfview
    - skype
    - spotify
    - sshd
    - terminator
    - vagrant
    - virtualbox
    - chbright
    - qpaeq-equalizer
    - shutter
    #- pulseaudio-equalizer

