---
- hosts: all
  remote_user: bxz
  sudo: yes
  roles:
    - common
    - compton
    - virtualbox
    - vagrant
    - spotify
    - qpdfview
    - skype
    - docker
    - terminator

- hosts: vps
  remote_user: bxz
  sudo: yes
  roles:
    - fail2ban
