---
- name: provision desktop
  hosts: lasus
  remote_user: bxz
  become: yes
  roles:
    #- common
    #- compton
    #- docker
    #- pulseaudio-equalizer
    #- qpdfview
    #- skype
    #- spotify
    #- terminator
    #- vagrant
    #- virtualbox
    - chbright
  become_user: root
  vars:
    docker_users: bxz
  roles:
    - common
    - compton
    - docker
    - pulseaudio-equalizer
    - qpdfview
    - skype
    - spotify
    - sshd
    - terminator
    - vagrant
    - virtualbox

