---
- hosts: all
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    docker_users: bxz
  roles:
    - common
    - compton
    - docker
    - pulseaudio-equalizer
    - qpdfview
    - skype
    - spotify
    - sshd
    - terminator
    - vagrant
    - virtualbox

