---
- hosts: all
  remote_user: bxz
  sudo: yes
  roles:
    - common
    - compton
    - docker
    - pulseaudio-equalizer
    - qpdfview
    - skype
    - spotify
    - terminator
    - vagrant
    - virtualbox

