---
- hosts: all
  remote_user: bxz
  sudo: yes
  tasks:

    - name: Remove unwanted packages
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - speech-dispatcher
        - parole
        - gmusicbrowser
        - xchat
        - abiword*
        - libabiword*
        - catfish
        - gimp*
        - libgimp*
        - gnumeric*
        - gnome-mines
        - gnome-sudoku
        - mousepad
        - pidgin*
        - xfburn
        - transmission*

    - name: Add numix (xfce4 theme) repository
      apt_repository: repo=ppa:numix/ppa state=present validate_certs=no

    - name: Add xorg-edgers repository
      apt_repository: repo=ppa:xorg-edgers/ppa state=present validate_certs=no

    - name: Add Spotify repository
      apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present

    - name: Add Spotify public key
      apt_key: keyserver=keyserver.ubuntu.com id=94558F59

    - name: Update repositories / upgrade packages
      apt: update_cache=yes upgrade=dist

    - name: Install new packages
      apt: name={{ item }} state=latest
      with_items:
        - ansible
        - vim-nox
        - git
        - htop
        - tree
        - tmux
        - nmap
        - iotop
        - lm-sensors
        - weechat
        - numix-gtk-theme
        - remmina
        - qpdfview
        - vlc
        - flashplugin-installer
        - bumblebee
        - bumblebee-nvidia
        - nvidia-340
        - spotify-client

    - name: Clone dotfiles git repo
      sudo: no
      git: repo=https://github.com/gsvitins/dotfiles.git dest=~/git/dotfiles

    - name: Copy .dotfiles from git repo to home folder
      sudo: no
      copy: src=~/git/dotfiles/ dest=~

    - name: Mount /dev/sda as /data
      sudo: yes
      mount: name=/data src=/dev/mapper/DATA-root fstype=ext4 state=mounted
