---
- hosts: all
  remote_user: bxz
  sudo: yes
  tasks:
    - name: Add numix (xfce4 theme) repository
      apt_repository: repo=ppa:numix/ppa state=present

    - name: Update repositories / upgrade packages
      apt: update_cache=yes upgrade=dist

    - name: Install new packages
      apt: name={{ item }} state=latest
      with_items:
        - ansible
        - vim-nox
        - git
        - htop
        - byobu
        - nmap
        - iotop
        - numix-gtk-theme
        - remmina

    - name: Remove unwanted packages
      apt: name={{ item }} state=absent purge=yes
      with_items:
        - speech-dispatcher
        - parole
        - gmusicbrowser
        - xchat
        - abiword*
        - libabiword*
        - catfish
        - gimp*
        - libgimp*
        - gnumeric*
        - gnome-mines
        - gnome-sudoku
        - mousepad
        - pidgin*
        - xfburn
        - transmission*

    - name: Clone dotfiles git repo
      sudo: no
      git: repo=https://github.com/gsvitins/dotfiles.git dest=~/git/dotfiles

    - name: copy .dotfiles from git repo to home folder
      sudo: no
      copy: src=~/git/dotfiles/ dest=~

    - name: Set Numix as default Xfce4 theme
      sudo: no
      lineinfile: >
        dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
        regexp=theme
        line='    <property name="theme" type="string" value="Numix"/>'
      lineinfile: >
        dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
        regexp='"ThemeName" type="string" value="'
        line='    <property name="ThemeName" type="string" value="Numix"/>'

    - name: Set display sleep/switch off timeout and disable light-locker
      sudo: no
      lineinfile: >
        dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
        regexp=dpms-on-ac-off
        line='   <property name="dpms-on-ac-off" type="uint" value="0"/>'
      lineinfile: >
        dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-power-manager.xml
        regexp=dpms-on-ac-sleep
        line='    <property name="dpms-on-ac-sleep" type="uint" value="0"/>'
      lineinfile: >
        dest=~/.config/autostart/light-locker.desktop
        regexp=Exec=
        line='Exec='







