---
- name: install vagrant
  hosts: localhost
  remote_user: bxz
  become: yes
  become_user: root
  vars:
    vagrant_version: 2.2.10
    vagrant_boxes:
      - ubuntu/bionic64
      - centos/7
      - centos/8
  roles:
    - vagrant

