---
- name: install vagrant
  hosts: localhost
  remote_user: gsvitins
  become: yes
  become_user: root
  vars:
    vagrant_version: "2.2.19"
    vagrant_boxes:
      - ubuntu/bionic64
      - centos/7
      - centos/8
  roles:
    - vagrant

