---
- name: download hashicorp pub key
  get_url:
    url: "https://apt.releases.hashicorp.com/gpg"
    dest: "/etc/apt/trusted.gpg.d/hashicorp-archive.gpg"
  become: yes
  become_user: root
  tags:
    - vagrant

- name: add apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp-archive.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    update_cache: yes
  become: yes
  become_user: root
  tags:
    - vagrant

- name: install vagrant
  package:
    name: vagrant
    state: latest
  become: yes
  become_user: root
  tags:
    - vagrant

- name: create vagrant homedir
  file:
    dest: "{{ ansible_user_dir }}/vagrant"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
    state: directory
  become: no
  tags:
    - vagrant

- name: copy Vagrantfile
  copy:
    src: Vagrantfile
    dest: "{{ ansible_user_dir }}/vagrant/Vagrantfile"
    backup: yes
  become: no
  tags:
    - vagrant
