---
- name: Check if vagrant is installed
  shell: dpkg-query -W vagrant
  register: vagrant_check
  ignore_errors: True

- name: Download vagrant package
  get_url: url=https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb dest={{ vagrant_dl_dir }}/vagrant_{{ vagrant_version }}_x86_64.deb
  when: vagrant_check.rc != 0

- name: Install vagrant
  apt: deb={{ vagrant_dl_dir }}/vagrant_{{ vagrant_version }}_x86_64.deb
  when: vagrant_check.rc != 0

- name: Create vagrant directory
  sudo: no
  file: path={{ vagrant_dir }} state=directory

- name: Copy Vagrantfile
  sudo: no
  copy: src=Vagrantfile dest={{ vagrant_dir }}/Vagrantfile

#- name: Copy ansible playbooks
#  sudo: no
#  copy: src=ansible/ dest={{ vagrant_dir}}/ansible/

  #- name: Add vagrant boxes
  #command: vagrant box add ubuntu/trusty64 chdir={{ vagrant_dir }}

