---
- hosts: all
  tasks:
    - name: Add compton repository 
      sudo: yes
      apt_repository: repo=ppa:richardgv/compton state=present

    - name: Install compton
      sudo: yes
      apt: name=compton state=latest

    - name: Add compton.conf
      sudo: no
      copy: src=files/compton.conf dest=~/.config/compton.conf

    - name: Enable compton on xfce session start
      sudo: no
      copy: src=files/compton.desktop dest=~/.config/autostart/compton.desktop

