---
- name: Install compton
  become: yes
  apt:
    name: compton
    state: latest

- name: Add compton.conf
  become: no
  copy:
    src: compton.conf
    dest: ~/.config/compton.conf

- name: Create autostart dir
  become: no
  file:
    path: ~/.config/autostart
    state: directory
    mode: 0755

- name: Enable compton on xfce session start
  become: no
  copy:
    src: compton.desktop
    dest: ~/.config/autostart/compton.desktop

