# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "s1" do |s1|
    s1.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "s1.bxz.lol"
    config.vm.network "public_network", bridge: "wlan0", ip: "10.10.10.111"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.synced_folder "/home/bxz/vagrant/", "/home/vagrant/shared"
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "s2.bxz.lol"
    config.vm.network "public_network", bridge: "wlan0", ip: "10.10.10.112"
    config.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
end
