# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "s1" do |s1|
    s1.vm.box = "ubuntu/trusty64"
    s1.vm.hostname = "s1"
    s1.vm.network "public_network", bridge: "wlan0", ip: "10.10.10.111"
  end

  config.vm.define "s2" do |s2|
    s2.vm.box = "ubuntu/trusty64"
    s2.vm.hostname = "s2"
    s2.vm.network "public_network", bridge: "wlan0", ip: "10.10.10.112"
   end

  config.vm.define "s3" do |s3|
    s3.vm.box = "ubuntu/trusty64"
    s3.vm.hostname = "s3"
    s3.vm.network "public_network", bridge: "wlan0", ip: "10.10.10.113"
   end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
  end

end

