---
- name: Add Spotify repository
  become: yes
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present

- name: Add Spotify public key
  become: yes
  apt_key: keyserver=keyserver.ubuntu.com id=0DF731E45CE24F27EEEB1450EFDC8610341D9410

- name: Install Spotify
  become: yes
  apt: name=spotify-client state=latest update_cache=yes

