---
- name: Update repositories
  apt: update_cache=yes

- name: Upgrade packages
  apt: upgrade=yes

- name: Install packages
  apt: name={{ item }} state=latest
  with_items:
    - vim-nox
    - tree
    - git
    - htop
    - tmux
