---
- name: Add Virtualbox repository
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present

- name: Add Virtualbox repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - 'https://www.virtualbox.org/download/oracle_vbox.asc'
    - 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'

- name: Install Virtualbox packages
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    update_cache: yes
    state: latest
    force: yes
