---
- name: Add Canonical partners repository
  apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu trusty partner' 
    state: present

- name: Install Skype packages
  apt:
    name: skypeforlinux
    state: latest

