---
<<<<<<< HEAD
- name: Add Canonical partners repository
  apt_repository:
    repo: 'deb http://archive.canonical.com/ubuntu trusty partner' 
    state: present

- name: Install Skype packages
  apt:
    name: skypeforlinux
    state: latest
=======
- name: Add Skype GPG key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
  become: yes

- name: Add Skype repo
  apt_repository:
    repo: deb https://repo.skype.com/deb stable main
    state: present
  become: yes

- name: Install Skype
  apt:
    name: skypeforlinux
    state: latest
  become: yes
>>>>>>> e5ad9563e838c2f8a44f6ebadec16991418b17a7

