---
- name: Add Skype GPG key
  apt_key:
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
  become: yes

- name: Add Skype repo
  apt_repository:
    repo: deb https://repo.skype.com/deb stable main
    state: present
  become: yes

- name: Install Skype
  apt:
    name: skypeforlinux
    state: latest
  become: yes

