---
- name: check if /etc/rc.local file exists
  stat:
    path: /etc/rc.local
  register: rclocal

- name: create rc.local file if it doesn't exist
  file:
    path: /etc/rc.local
    state: touch
  when: rclocal.stat.exists == False 

- name: Disable bluetooth adapter on startup
  lineinfile:
    path: /etc/rc.local
    state: present
    line: "rfkill block bluetooth"
