---
- name: Remove unwanted packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - speech-dispatcher
    - parole
    - gmusicbrowser
    - xchat
    - abiword*
    - libabiword*
    - libreoffice*
    - catfish
    - gimp*
    - libgimp*
    - gnumeric*
    - gnome-mines
    - gnome-sudoku
    - mousepad
    - pidgin*
    - xfburn
    - transmission*
    - evince

- name: Update repositories / upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install new packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - vim-nox
    - git
    - htop
    - glances
    - tree
    - tmux
    - curl
    - nmap
    - whois
    - iotop
    - iftop
    - smartmontools
    - ipython
    - flake8
    - python-flake8
    - python-pip
    - lm-sensors
    - weechat-curses
    - remmina
    - vlc
    - mplayer
    - qbittorrent
    - chromium-browser
    - flashplugin-installer
    - keepass2
    - rar
    - apcalc
    - glances

