---
- name: Remove unwanted packages
  apt:
    state: absent
    purge: yes
    pkg:
      - speech-dispatcher
      - parole
      - gmusicbrowser
      - xchat
      - abiword*
      - libabiword*
      - libreoffice*
      - catfish
      - gimp*
      - libgimp*
      - gnumeric*
      - gnome-mines
      - gnome-sudoku
      - mousepad
      - pidgin*
      - xfburn
      - transmission*
      - evince

- name: Update repositories / upgrade packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install apt packages
  apt:
    state: latest
    pkg:
      - ansible
      - vim-nox
      - git
      - htop
      - glances
      - tree
      - tmux
      - curl
      - wget
      - nmap
      - ngrep
      - whois
      - iotop
      - iftop
      - smartmontools
      - ipython3
      - python3-pip
      - python3-venv
      - lm-sensors
      - vlc
      - qbittorrent
      - chromium-browser
      - keepass2
      - rar
      - tldr

- name: Install snap packages
  snap:
    state: present
    classic: yes
    name:
      - code
      - sublime-text
      - remmina
      - spotify
