---
- name: add docker repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' update_cache=yes

- name: install docker engine
  apt: name=docker-engine state=latest force=yes

- name: start docker service
  service: name=docker state=started
